import { useEffect, useState } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { PageLayout } from "@/components/how2getrich/PageLayout";
import { DottedSpine } from "@/components/how2getrich/DottedSpine";
import {
  generateH2GRPlan,
  getH2GRPlan,
  getH2GRStatus,
} from "@/lib/h2gr-plan";
import { Wordmark } from "@/components/how2getrich/Wordmark";

// Inline type + static fallback so this route doesn't pull the
// server-side ideas-generator module (and its `process.env` access)
// into the client bundle. The server function returns the same shape.
type H2GRPlanStep = { day: string; title: string; body: string };
const STATIC_PLAN: H2GRPlanStep[] = [
  { day: "day 1", title: "Choose one boring skill people already pay for", body: "examples: editing, landing pages, thumbnails, ads, automation" },
  { day: "day 2", title: "Pick one specific customer with a painful problem", body: "do not build for everyone" },
  { day: "day 3", title: "Find 20 examples of people already making money this way", body: "steal the pattern, not the product" },
  { day: "day 4", title: "Write the dumbest possible offer", body: '"I will help [person] get [result] without [pain]"' },
  { day: "day 5", title: "Make a one-page site explaining the offer", body: "headline, proof, price, contact button" },
  { day: "day 6", title: "Create one tiny sample result", body: "mockup, demo, before/after, screenshot, short video" },
  { day: "day 7", title: "Send the offer to 25 real people", body: "no ads yet. no logo redesign. talk to humans." },
];

export const Route = createFileRoute("/todo")({
  head: () => ({
    meta: [
      { title: "To Do — how2getrich.online" },
      { name: "description", content: "Your tailored 7-day plan." },
    ],
  }),
  validateSearch: (search: Record<string, unknown>) => ({
    s: typeof search.s === "string" ? search.s : "",
    // Which month's plan we're viewing. 1 = the free lead magnet.
    // 2+ requires a paid tier and gets gated server-side.
    month:
      typeof search.month === "number"
        ? Math.max(1, Math.min(12, Math.round(search.month)))
        : typeof search.month === "string" && /^\d+$/.test(search.month)
          ? Math.max(1, Math.min(12, parseInt(search.month, 10)))
          : 1,
    // Set to "1" by Stripe Checkout's success_url so we can show a
    // welcome banner the first time the user lands here after paying.
    subscribed:
      typeof search.subscribed === "string" ? search.subscribed : "",
  }),
  component: TodoPlan,
});

/**
 * Screen 2 — the tailored 7-day plan. After the user submits Screen 1
 * they land here. The plan is generated by Claude via the
 * generateH2GRPlan server function (reusing the same Anthropic API
 * pipeline that powers the LaunchFly Blueprint generator) and cached
 * in localStorage so we don't burn tokens regenerating on every
 * navigation.
 *
 * Layout: same chrome as Screen 1 (sidebar + right spine + "More info →")
 * with the plan rendered as a list, and the "Get 365 days →" upsell
 * tucked at the bottom.
 */

function TodoPlan() {
  // session_id from the ?s= query param (or localStorage as a backup,
  // for users who hit /todo directly without coming from /).
  const { s: sessionIdFromUrl, month, subscribed } = Route.useSearch();
  const navigate = useNavigate();

  // Echo the user's answer back at the top of the plan once we have it.
  const [tellMe, setTellMe] = useState<string>("");
  const [plan, setPlan] = useState<H2GRPlanStep[]>(STATIC_PLAN);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  // Tier-aware state for the CTA + "what month am I on" header.
  const [tier, setTier] = useState<"free" | "basic" | "premium">("free");
  const [monthsGenerated, setMonthsGenerated] = useState<number[]>([]);
  const [generatingNextMonth, setGeneratingNextMonth] = useState(false);

  useEffect(() => {
    let sessionId = sessionIdFromUrl;
    let input = "";
    try {
      if (!sessionId) sessionId = window.localStorage.getItem("h2gr:sessionId") ?? "";
      input = window.localStorage.getItem("h2gr:tellMeAboutYourself") ?? "";
    } catch {
      /* private mode */
    }
    setTellMe(input);

    // If we have neither a session nor an input, there's nothing to
    // generate — leave the static plan visible.
    if (!sessionId && !input) {
      setLoading(false);
      return;
    }

    let cancelled = false;
    (async () => {
      try {
        // Kick off the tier/months lookup in parallel so the CTA is
        // accurate as soon as the plan finishes loading.
        const statusPromise = sessionId
          ? getH2GRStatus({ data: { sessionId } }).catch(() => null)
          : Promise.resolve(null);

        // Try the persisted plan first — same session id + month returns
        // the exact plan we already paid Claude for.
        if (sessionId) {
          const cached = await getH2GRPlan({ data: { sessionId, month } });
          if (cancelled) return;
          if (cached.ok && Array.isArray(cached.plan)) {
            setPlan(cached.plan);
            if (cached.input) setTellMe(cached.input);
            await applyStatus(await statusPromise);
            setLoading(false);
            return;
          }
          if (!cached.ok && cached.reason === "requires-subscription") {
            // Hard-redirect free users who deep-linked into a paid month
            // back to the upgrade page so they see the price before the
            // empty-state confuses them.
            navigate({
              to: "/todo/upgrade",
              search: { s: sessionId },
            });
            return;
          }
        }

        // Cache miss → generate + persist. Server handles the Claude
        // call and writes to D1 for future loads.
        const res = await generateH2GRPlan({
          data: { sessionId: sessionId ?? "", input, month },
        });
        if (cancelled) return;
        if (res.ok && Array.isArray(res.plan)) setPlan(res.plan);
        else if (!res.ok && res.reason === "requires-subscription") {
          navigate({
            to: "/todo/upgrade",
            search: { s: sessionId ?? "" },
          });
          return;
        }
        await applyStatus(await statusPromise);
      } catch (err) {
        if (cancelled) return;
        console.error("[todo] plan generation failed", err);
        setError("Couldn't reach the plan generator — showing the default plan.");
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();

    // eslint-disable-next-line @typescript-eslint/no-inner-declarations
    async function applyStatus(
      status: { tier: "free" | "basic" | "premium"; monthsGenerated: number[] } | null,
    ) {
      if (cancelled || !status) return;
      setTier(status.tier);
      setMonthsGenerated(status.monthsGenerated);
    }

    return () => {
      cancelled = true;
    };
  }, [sessionIdFromUrl, month, navigate]);

  // Generate Month N+1 on demand (subscribers only).
  async function onGenerateNextMonth() {
    const sessionId =
      sessionIdFromUrl ||
      (typeof window !== "undefined"
        ? window.localStorage.getItem("h2gr:sessionId") ?? ""
        : "");
    if (!sessionId || generatingNextMonth) return;
    const input =
      typeof window !== "undefined"
        ? window.localStorage.getItem("h2gr:tellMeAboutYourself") ?? ""
        : "";
    setGeneratingNextMonth(true);
    try {
      const nextMonth = month + 1;
      const res = await generateH2GRPlan({
        data: { sessionId, input, month: nextMonth },
      });
      if (res.ok) {
        navigate({
          to: "/todo",
          search: { s: sessionId, month: nextMonth },
        });
      } else if (res.reason === "requires-subscription") {
        navigate({ to: "/todo/upgrade", search: { s: sessionId } });
      } else {
        window.alert(`Couldn't generate Month ${nextMonth}: ${res.reason}`);
      }
    } finally {
      setGeneratingNextMonth(false);
    }
  }

  const isSubscribed = tier === "basic" || tier === "premium";
  const nextMonth = month + 1;
  const nextMonthExists = monthsGenerated.includes(nextMonth);

  return (
    <PageLayout
      rightRail={loading ? undefined : <RightRailWithMoreInfo />}
    >
      {/* While Claude is generating: brand only (Wordmark) + loader.
          The "To Do:" header, the "based on: ..." echo, and the
          right-rail "More info" are intentionally hidden so the
          waiting screen is clean and obviously a transitional state. */}
      {loading ? (
        <>
          <Wordmark />
          <div
            className="mt-[64px] flex w-full max-w-[420px] flex-col items-center gap-[14px]"
            style={{
              fontFamily:
                '"VT323", "JetBrains Mono", ui-monospace, "SF Mono", monospace',
            }}
          >
            <span className="text-[15px] tracking-wide text-white/70">
              generating your plan…
            </span>
            <div className="h-[3px] w-full overflow-hidden rounded-full bg-white/10">
              <div className="h-full w-[35%] animate-h2gr-loader rounded-full bg-white/85" />
            </div>
          </div>
        </>
      ) : (
        <>
          <Header />

          {error && (
            <p
              className="mt-[12px] text-[14px] text-white/40"
              style={{
                fontFamily:
                  '"VT323", "JetBrains Mono", ui-monospace, "SF Mono", monospace',
              }}
            >
              {error}
            </p>
          )}
          <ol
            className="mt-[28px] flex w-full max-w-[407px] flex-col gap-[16px] text-white/90"
            style={{
              fontFamily:
                '"VT323", "JetBrains Mono", ui-monospace, "SF Mono", monospace',
            }}
          >
            {plan.map((step, i) => (
              <li key={step.day}>
                {/* Whole row is a clickable Link → /todo/{N}?s=…
                    -mx-3 px-3 -my-1 py-1 widens the click hit area
                    beyond the visible text without affecting layout;
                    rounded + hover bg gives obvious cursor feedback. */}
                <Link
                  to="/todo/$day"
                  params={{ day: String(i + 1) }}
                  search={{ s: sessionIdFromUrl, month }}
                  className="group -mx-3 -my-1 flex cursor-pointer items-baseline gap-[8px] rounded-[4px] px-3 py-1 leading-snug transition hover:bg-white/[0.04]"
                >
                  <span className="w-[44px] shrink-0 text-[13.2px] text-white/55 transition group-hover:text-white/80">
                    {step.day}:
                  </span>
                  <span className="flex-1 text-[13.6px] text-white/90 transition group-hover:text-white group-hover:underline group-hover:decoration-white/40 group-hover:underline-offset-[3px]">
                    {step.title}
                  </span>
                </Link>
              </li>
            ))}
          </ol>
        </>
      )}

      {/* Just-paid welcome banner — shown once on the redirect from
          Stripe Checkout (success_url includes ?subscribed=1). */}
      {!loading && subscribed === "1" && (
        <div
          className="mt-[28px] rounded-[6px] border border-amber-200/30 bg-amber-200/10 px-[18px] py-[14px] text-center text-[14px] text-amber-100"
          style={{
            fontFamily:
              '"VT323", "JetBrains Mono", ui-monospace, "SF Mono", monospace',
          }}
        >
          you&apos;re in. check your email for a sign-in link so you can
          access this plan from any device.
        </div>
      )}

      {/* Tier-aware bottom CTA. Three states:
          1. Free user, month 1 → "Continue past Month 1" → /todo/upgrade
          2. Subscribed, next month already generated → "View Month N+1"
          3. Subscribed, next month not yet → "Generate Month N+1" (calls server) */}
      {!loading && (
        <div className="mt-[40px] flex w-full justify-center">
          {!isSubscribed && month === 1 ? (
            <Link
              to="/todo/upgrade"
              search={{ s: sessionIdFromUrl }}
              className="group inline-flex h-[80px] w-[437px] max-w-full items-center justify-center gap-[16px] rounded-[6px] bg-white text-[16px] text-black/80 transition hover:text-black focus:outline-none focus:ring-2 focus:ring-white/40"
              style={{
                fontFamily:
                  '"VT323", "JetBrains Mono", ui-monospace, "SF Mono", monospace',
              }}
            >
              <span>Continue past Month 1</span>
              <Arrow className="h-[9px] w-[44px] text-black" />
            </Link>
          ) : isSubscribed && nextMonthExists ? (
            <Link
              to="/todo"
              search={{ s: sessionIdFromUrl, month: nextMonth }}
              className="group inline-flex h-[80px] w-[437px] max-w-full items-center justify-center gap-[16px] rounded-[6px] bg-white text-[16px] text-black/80 transition hover:text-black focus:outline-none focus:ring-2 focus:ring-white/40"
              style={{
                fontFamily:
                  '"VT323", "JetBrains Mono", ui-monospace, "SF Mono", monospace',
              }}
            >
              <span>View Month {nextMonth}</span>
              <Arrow className="h-[9px] w-[44px] text-black" />
            </Link>
          ) : isSubscribed ? (
            <button
              type="button"
              onClick={onGenerateNextMonth}
              disabled={generatingNextMonth}
              className="group inline-flex h-[80px] w-[437px] max-w-full items-center justify-center gap-[16px] rounded-[6px] bg-white text-[16px] text-black/80 transition hover:text-black focus:outline-none focus:ring-2 focus:ring-white/40 disabled:cursor-wait disabled:opacity-60"
              style={{
                fontFamily:
                  '"VT323", "JetBrains Mono", ui-monospace, "SF Mono", monospace',
              }}
            >
              <span>
                {generatingNextMonth
                  ? `generating Month ${nextMonth}…`
                  : `Generate Month ${nextMonth}`}
              </span>
              {!generatingNextMonth && (
                <Arrow className="h-[9px] w-[44px] text-black" />
              )}
            </button>
          ) : (
            /* Subscribed user viewing a paid month — show "Manage" link. */
            <Link
              to="/account"
              className="text-[14px] text-white/45 transition hover:text-white/70"
              style={{
                fontFamily:
                  '"VT323", "JetBrains Mono", ui-monospace, "SF Mono", monospace',
              }}
            >
              manage subscription →
            </Link>
          )}
        </div>
      )}

      {/* "Month N of …" indicator, shown only past Month 1 so the free
          page stays uncluttered. */}
      {!loading && month > 1 && (
        <p
          className="mt-[16px] text-center text-[13px] text-white/40"
          style={{
            fontFamily:
              '"VT323", "JetBrains Mono", ui-monospace, "SF Mono", monospace',
          }}
        >
          Month {month}
        </p>
      )}
    </PageLayout>
  );
}

/** "To Do:" header in JetBrains Mono, centered. */
function Header() {
  return (
    <h1
      className="mt-[18px] text-[22px] leading-tight text-white"
      style={{
        fontFamily:
          '"VT323", "JetBrains Mono", ui-monospace, "SF Mono", monospace',
      }}
    >
      To Do:
    </h1>
  );
}

/**
 * Floating right rail: dotted spine + "More info →" mid-height.
 * Anchored to the viewport RIGHT but pulled inward 140-165px so it
 * sits closer to the stage instead of hugging the viewport edge.
 */
export function RightRailWithMoreInfo() {
  return (
    <>
      <DottedSpine className="absolute top-[90px] bottom-[60px] right-[140px] z-10" />
      <div
        className="absolute right-[165px] top-[290px] z-10 flex flex-col items-end gap-[8px] text-white/40"
        style={{
          fontFamily:
            '"VT323", "JetBrains Mono", ui-monospace, "SF Mono", monospace',
        }}
      >
        <span className="text-[20px] leading-none">More info</span>
        <Arrow className="h-[5px] w-[44px] text-white/40" />
      </div>
    </>
  );
}

/** Thin right-pointing arrow — used in the CTA + "More info →". */
export function Arrow({ className = "" }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 63 6"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.2"
      strokeLinecap="square"
      strokeLinejoin="miter"
      className={className}
      aria-hidden
    >
      <path d="M0 3h60" />
      <path d="M57 0l5 3-5 3" fill="currentColor" />
    </svg>
  );
}
