/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodoRouteImport } from './routes/todo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodoUpgradeRouteImport } from './routes/todo_.upgrade'
import { Route as TodoDayRouteImport } from './routes/todo_.$day'

const TodoRoute = TodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoUpgradeRoute = TodoUpgradeRouteImport.update({
  id: '/todo_/upgrade',
  path: '/todo/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoDayRoute = TodoDayRouteImport.update({
  id: '/todo_/$day',
  path: '/todo/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/todo': typeof TodoRoute
  '/todo/$day': typeof TodoDayRoute
  '/todo/upgrade': typeof TodoUpgradeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/todo': typeof TodoRoute
  '/todo/$day': typeof TodoDayRoute
  '/todo/upgrade': typeof TodoUpgradeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/todo': typeof TodoRoute
  '/todo_/$day': typeof TodoDayRoute
  '/todo_/upgrade': typeof TodoUpgradeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/todo' | '/todo/$day' | '/todo/upgrade'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/todo' | '/todo/$day' | '/todo/upgrade'
  id: '__root__' | '/' | '/todo' | '/todo_/$day' | '/todo_/upgrade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TodoRoute: typeof TodoRoute
  TodoDayRoute: typeof TodoDayRoute
  TodoUpgradeRoute: typeof TodoUpgradeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo_/upgrade': {
      id: '/todo_/upgrade'
      path: '/todo/upgrade'
      fullPath: '/todo/upgrade'
      preLoaderRoute: typeof TodoUpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo_/$day': {
      id: '/todo_/$day'
      path: '/todo/$day'
      fullPath: '/todo/$day'
      preLoaderRoute: typeof TodoDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TodoRoute: TodoRoute,
  TodoDayRoute: TodoDayRoute,
  TodoUpgradeRoute: TodoUpgradeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
